In [3]:
import pandas as pd

In [4]:
data = pd.read_csv('MERGED2017_18_PP.csv') # loading csv file using pandas

C:\Users\vyshu\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (1729) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [5]:
data.shape # count 0f rows and columns

(7112, 1986)

In [6]:
len(data) # number of rows in csv file

7112

In [7]:
len(data.columns) # number of columns in csv file

1986

To see first 5 colleges use 'first' command

In [8]:
data.head(5)

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMENRUP_PARTTIME_POOLED_SUPP,FTFTPCTPELL,FTFTPCTFLOAN,UG12MN,G12MN,SCUGFFN,POOLYRS_FTFTAIDPCT,FTFTPCTPELL_POOLED_SUPP,FTFTPCTFLOAN_POOLED_SUPP,SCUGFFN_POOLED
0,100654,100200,1002,Alabama A & M University,Normal,AL,35762,NaN,NaN,NaN,...,NaN,0.7106,0.7418,5207.0,1185.0,1410.0,NaN,NaN,NaN,NaN
1,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,NaN,NaN,NaN,...,NaN,0.4009,0.5488,13308.0,9888.0,1948.0,NaN,NaN,NaN,NaN
2,100690,2503400,25034,Amridge University,Montgomery,AL,36117-3553,NaN,NaN,NaN,...,NaN,0.5000,0.5000,431.0,437.0,4.0,NaN,NaN,NaN,NaN
3,100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,35899,NaN,NaN,NaN,...,NaN,0.2012,0.4231,7519.0,2378.0,1203.0,NaN,NaN,NaN,NaN
4,100724,100500,1005,Alabama State University,Montgomery,AL,36104-0271,NaN,NaN,NaN,...,NaN,0.7594,0.7402,5229.0,687.0,1143.0,NaN,NaN,NaN,NaN

To see last 5 colleges use 'tail' command

In [9]:
data.tail(5)

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMENRUP_PARTTIME_POOLED_SUPP,FTFTPCTPELL,FTFTPCTFLOAN,UG12MN,G12MN,SCUGFFN,POOLYRS_FTFTAIDPCT,FTFTPCTPELL_POOLED_SUPP,FTFTPCTFLOAN_POOLED_SUPP,SCUGFFN_POOLED
7107,48312404,108163,1081,Arizona State University at Yuma,Yuma,AZ,853656900,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7108,48387801,4223701,42237,Bay Area Medical Academy - San Jose Satellite ...,San Jose,CA,95113,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7109,48400201,4228101,42281,High Desert Medical College - Bakerfield,Bakersfield,CA,93301,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7110,48778201,4221501,42215,BCI - Malden,Malden,MA,021480000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7111,49005401,4182601,41826,HCI College - Fort Lauderdale Campus,Fort Lauderdale,FL,33309,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

random sample of 5 colleges

In [10]:
data.sample(5)

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMENRUP_PARTTIME_POOLED_SUPP,FTFTPCTPELL,FTFTPCTFLOAN,UG12MN,G12MN,SCUGFFN,POOLYRS_FTFTAIDPCT,FTFTPCTPELL_POOLED_SUPP,FTFTPCTFLOAN_POOLED_SUPP,SCUGFFN_POOLED
537,126748,135900,1359,Colorado Northwestern Community College,Rangely,CO,81648-3598,NaN,NaN,NaN,...,NaN,0.4094,0.4497,1678.0,NaN,149.0,NaN,NaN,NaN,NaN
3061,213996,329800,3298,Messiah College,Mechanicsburg,PA,17055,NaN,NaN,NaN,...,NaN,0.1898,0.7007,2866.0,689.0,685.0,NaN,NaN,NaN,NaN
6191,482228,3862600,38626,Veritas Baptist College,Greendale,IN,47025,NaN,NaN,NaN,...,NaN,0.8000,0.4000,113.0,29.0,5.0,NaN,NaN,NaN,NaN
4758,434496,3293300,32933,Strand College of Hair Design,Myrtle Beach,SC,29572,NaN,NaN,NaN,...,NaN,0.5398,0.4956,113.0,NaN,113.0,NaN,NaN,NaN,NaN
6445,486956,638517,6385,Chamberlain University-New Jersey,North Brunswick,NJ,08902-3492,NaN,NaN,NaN,...,NaN,0.0000,1.0000,500.0,NaN,1.0,NaN,NaN,NaN,NaN

A smaller data frame with the following 9 variables to get easy

In [11]:
df = data[['UNITID','INSTNM','CITY','STABBR','ZIP','ADM_RATE','UGDS','TUITIONFEE_IN','MN_EARN_WNE_P10']].copy()

In [12]:
df

,UNITID,INSTNM,CITY,STABBR,ZIP,ADM_RATE,UGDS,TUITIONFEE_IN,MN_EARN_WNE_P10
0,100654,Alabama A & M University,Normal,AL,35762,0.9027,4824.0,9857.0,NaN
1,100663,University of Alabama at Birmingham,Birmingham,AL,35294-0110,0.9181,12866.0,8328.0,NaN
2,100690,Amridge University,Montgomery,AL,36117-3553,NaN,318.0,6900.0,NaN
3,100706,University of Alabama in Huntsville,Huntsville,AL,35899,0.8123,6917.0,10280.0,NaN
4,100724,Alabama State University,Montgomery,AL,36104-0271,0.9787,4189.0,11068.0,NaN
...,...,...,...,...,...,...,...,...,...
7107,48312404,Arizona State University at Yuma,Yuma,AZ,853656900,NaN,NaN,NaN,NaN
7108,48387801,Bay Area Medical Academy - San Jose Satellite ...,San Jose,CA,95113,NaN,NaN,NaN,NaN
7109,48400201,High Desert Medical College - Bakerfield,Bakersfield,CA,93301,NaN,NaN,NaN,NaN
7110,48778201,BCI - Malden,Malden,MA,021480000,NaN,NaN,NaN,NaN
7111,49005401,HCI College - Fort Lauderdale Campus,Fort Lauderdale,FL,33309,NaN,NaN,22575.0,NaN

# Definitions for the above 9 variables

**UNITID** - Unit ID for institution, it is a integer data type

**INSTNM** - Institution names, it is a string data type

**CITY** - City names, it is a string data type

**STABBR** - State postcode, it is a string data type

**ZIP** - Zip codes, it is a string data type

**ADM_RATE** - Admission rate, it is a float data type. 
Colleges report to IPEDS their Fall admissions rate, defined as the number of admitted undergraduates divided by the number of
undergraduates who applied. For institutions with multiple branches, ADM_RATE includes the admissions rate at each campus.
(Fall 2017, reported in IPEDS DCY2017-18)

**UGDS** - Number of Undergraduate Students, it is a integer data type. 
This element (UGDS) includes the number of degree/certificate-seeking undergraduates enrolled in the fall, as reported in the IPEDS Fall Enrollment component.
(Fall 2017, reported in IPEDS DCY2017-18)

**TUITIONFEE_IN** - Tuition and Fees,  the cost data include the tuition and required fees of the institution. They are provided for in-state students (TUITIONFEE_IN).
(AcadYr 2017-18, reported in IPEDS DCY2017-18)

**MN_EARN_WNE_P10** - Mean and Median Earnings, it is a integer data type.
Mean (MN_EARN_WNE_P*) and median (MD_EARN_WNE_P*) earnings are for the institutional aggregate of all federally aided students who enroll in an institution each year and who are employed but not enrolled.

In [13]:
df.head(10) # first 10 rows of new data frame

,UNITID,INSTNM,CITY,STABBR,ZIP,ADM_RATE,UGDS,TUITIONFEE_IN,MN_EARN_WNE_P10
0,100654,Alabama A & M University,Normal,AL,35762,0.9027,4824.0,9857.0,NaN
1,100663,University of Alabama at Birmingham,Birmingham,AL,35294-0110,0.9181,12866.0,8328.0,NaN
2,100690,Amridge University,Montgomery,AL,36117-3553,NaN,318.0,6900.0,NaN
3,100706,University of Alabama in Huntsville,Huntsville,AL,35899,0.8123,6917.0,10280.0,NaN
4,100724,Alabama State University,Montgomery,AL,36104-0271,0.9787,4189.0,11068.0,NaN
5,100751,The University of Alabama,Tuscaloosa,AL,35487-0100,0.5330,32387.0,10780.0,NaN
6,100760,Central Alabama Community College,Alexander City,AL,35010,NaN,1404.0,4440.0,NaN
7,100812,Athens State University,Athens,AL,35611,NaN,2801.0,NaN,NaN
8,100830,Auburn University at Montgomery,Montgomery,AL,36117-3596,0.8240,4211.0,8020.0,NaN
9,100858,Auburn University,Auburn,AL,36849,0.8393,23391.0,10968.0,NaN

In [14]:
df.tail(10) # # last 10 rows of new data frame

,UNITID,INSTNM,CITY,STABBR,ZIP,ADM_RATE,UGDS,TUITIONFEE_IN,MN_EARN_WNE_P10
7102,48154401,National Personal Training Institute of Cleveland,Highland Heights,OH,44143,NaN,NaN,NaN,NaN
7103,48305401,Barber School of Pittsburgh - Ambridge,Ambridge,PA,150030000,NaN,NaN,NaN,NaN
7104,48312401,Arizona State University at Tucson,Tucson,AZ,857454284,NaN,NaN,NaN,NaN
7105,48312402,Arizona State University - ASU Colleges at Lak...,Lake Havasu City,AZ,864036877,NaN,NaN,6904.0,NaN
7106,48312403,Arizona State University at The Gila Valley,Thatcher,AZ,855525545,NaN,NaN,NaN,NaN
7107,48312404,Arizona State University at Yuma,Yuma,AZ,853656900,NaN,NaN,NaN,NaN
7108,48387801,Bay Area Medical Academy - San Jose Satellite ...,San Jose,CA,95113,NaN,NaN,NaN,NaN
7109,48400201,High Desert Medical College - Bakerfield,Bakersfield,CA,93301,NaN,NaN,NaN,NaN
7110,48778201,BCI - Malden,Malden,MA,021480000,NaN,NaN,NaN,NaN
7111,49005401,HCI College - Fort Lauderdale Campus,Fort Lauderdale,FL,33309,NaN,NaN,22575.0,NaN

In [15]:
df.sample(10) # random sample of 10 colleges

,UNITID,INSTNM,CITY,STABBR,ZIP,ADM_RATE,UGDS,TUITIONFEE_IN,MN_EARN_WNE_P10
1103,151102,Purdue University Fort Wayne,Fort Wayne,IN,46805-1499,0.9441,7708.0,8330.0,NaN
4264,376446,Academy of Hair Technology,Greenville,SC,29615-2363,NaN,87.0,NaN,NaN
6236,483212,Louisiana Delta Community College,Monroe,LA,71203,NaN,2869.0,4158.0,NaN
573,128151,Pickens Technical College,Aurora,CO,80011-9307,NaN,988.0,4510.0,NaN
2092,184746,Hohokus School of Trade and Technical Sciences,Paterson,NJ,07513,NaN,190.0,NaN,NaN
5189,447704,Tucson College of Beauty,Tucson,AZ,85705,NaN,69.0,NaN,NaN
1153,153074,Capri College-Dubuque,Dubuque,IA,52004-0873,NaN,167.0,NaN,NaN
2418,196130,SUNY Buffalo State,Buffalo,NY,14222,0.5756,8395.0,7976.0,NaN
1195,153861,Maharishi University of Management,Fairfield,IA,52557,0.8889,320.0,27530.0,NaN
4412,405854,Rabbinical College of Ohr Shimon Yisroel,Brooklyn,NY,11211,NaN,227.0,13600.0,NaN

In [16]:
umbc = df.loc[df['INSTNM'].str.contains("University of Maryland-Baltimore County")]
umbc

,UNITID,INSTNM,CITY,STABBR,ZIP,ADM_RATE,UGDS,TUITIONFEE_IN,MN_EARN_WNE_P10
1478,163268,University of Maryland-Baltimore County,Baltimore,MD,21250,0.6021,11130.0,11518.0,NaN

In [17]:
Collegepark = df.loc[df['INSTNM'].str.contains("University of Maryland-College Park")]
Collegepark

,UNITID,INSTNM,CITY,STABBR,ZIP,ADM_RATE,UGDS,TUITIONFEE_IN,MN_EARN_WNE_P10
1479,163286,University of Maryland-College Park,College Park,MD,20742,0.445,29273.0,10399.0,NaN

In [18]:
Loyola = df.loc[df['INSTNM'].str.contains("Loyola University Maryland")]
Loyola

,UNITID,INSTNM,CITY,STABBR,ZIP,ADM_RATE,UGDS,TUITIONFEE_IN,MN_EARN_WNE_P10
1475,163046,Loyola University Maryland,Baltimore,MD,21210-2699,0.7528,3903.0,47560.0,NaN

In [19]:
john = df.loc[df['INSTNM'].str.contains("Johns Hopkins University")]
john

,UNITID,INSTNM,CITY,STABBR,ZIP,ADM_RATE,UGDS,TUITIONFEE_IN,MN_EARN_WNE_P10
1473,162928,Johns Hopkins University,Baltimore,MD,21218-2688,0.1254,5663.0,52170.0,NaN

calculating max, min, average in above 4 colleges

In [20]:
x = pd.concat([john, Loyola, Collegepark, umbc])

In [26]:
col = x["TUITIONFEE_IN"]
big = col.max() # finding maximum of tutuionfee in above four colleges
big

52170.0

In [27]:
col = x["TUITIONFEE_IN"]
small = col.min() # finding minimum of tutuionfee in above four colleges
small

10399.0

In [29]:
x["TUITIONFEE_IN"].mean() # finding average of tutuionfee in above four colleges

30411.75

# Smaller dataset for 5 STATES colleges

In [30]:
p = df[df["STABBR"] == "PA"]
p

,UNITID,INSTNM,CITY,STABBR,ZIP,ADM_RATE,UGDS,TUITIONFEE_IN,MN_EARN_WNE_P10
2933,210474,Jolie Hair and Beauty Academy-Hazleton,Hazleton,PA,18201,NaN,61.0,NaN,NaN
2934,210492,Bryn Athyn College of the New Church,Bryn Athyn,PA,19009-0711,0.8755,323.0,21126.0,NaN
2935,210508,Academy of Vocal Arts,Philadelphia,PA,19103-6685,NaN,NaN,NaN,NaN
2936,210571,Albright College,Reading,PA,19612-5234,0.5004,1999.0,43454.0,NaN
2937,210599,All-State Career School,Essington,PA,19029,NaN,306.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
7023,44378405,Strayer University-Warrendale Campus,Warrendale,PA,15086,NaN,NaN,13857.0,NaN
7024,44378406,Strayer University-Allentown Campus,Center Valley,PA,18034,NaN,NaN,13857.0,NaN
7063,45794301,Somerset County Technology Center - Bedford Site,Bedford,PA,15522,NaN,NaN,NaN,NaN
7089,47503308,Relay Graduate School of Education - Philadelp...,Philadelphia,PA,191224906,NaN,NaN,NaN,NaN
7103,48305401,Barber School of Pittsburgh - Ambridge,Ambridge,PA,150030000,NaN,NaN,NaN,NaN

In [31]:
v = df[df["STABBR"] == "VA"]
v

,UNITID,INSTNM,CITY,STABBR,ZIP,ADM_RATE,UGDS,TUITIONFEE_IN,MN_EARN_WNE_P10
3627,231280,Paul Mitchell the School-Roanoke,Roanoke,VA,24015,NaN,84.0,NaN,NaN
3628,231411,Advanced Technology Institute,Virginia Beach,VA,23462,0.7954,464.0,13250.0,NaN
3629,231420,Averett University,Danville,VA,24541,0.6102,908.0,33350.0,NaN
3630,231536,Blue Ridge Community College,Weyers Cave,VA,24486-0080,NaN,3054.0,5252.0,NaN
3631,231554,Bluefield College,Bluefield,VA,24605,0.9112,874.0,24800.0,NaN
...,...,...,...,...,...,...,...,...,...
6969,24893411,ECPI University-Virginia Beach Health Sciences,Virginia Beach,VA,234621603,NaN,NaN,15261.0,NaN
6970,24893412,ECPI University-Richmond South,Richmond,VA,232361603,NaN,NaN,14985.0,NaN
6971,24893413,ECPI University-Innsbrook,Glen Allen,VA,230601603,NaN,NaN,15263.0,NaN
6972,24893414,ECPI University-Richmond West,Richmond,VA,232941603,NaN,NaN,16039.0,NaN
6973,24893415,ECPI University - Roanoke,Roanoke,VA,240121603,NaN,NaN,15525.0,NaN

In [32]:
m = df[df["STABBR"] == "MD"]
m

,UNITID,INSTNM,CITY,STABBR,ZIP,ADM_RATE,UGDS,TUITIONFEE_IN,MN_EARN_WNE_P10
1446,161651,Aesthetics Institute of Cosmetology,Gaithersburg,MD,20877,NaN,25.0,NaN,NaN
1447,161688,Allegany College of Maryland,Cumberland,MD,21502-2596,NaN,1990.0,3940.0,NaN
1448,161767,Anne Arundel Community College,Arnold,MD,21012-1895,NaN,11294.0,4646.0,NaN
1449,161776,Brightwood College-Towson,Towson,MD,21286-2201,NaN,309.0,NaN,NaN
1450,161800,Award Beauty School,Hagerstown,MD,21740-5610,NaN,157.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
6800,16210401,Cecil College - Elkton Station,Elkton,MD,219215535,NaN,NaN,4005.0,NaN
7004,43018401,Strayer University-Rockville Campus,Rockville,MD,20850,NaN,NaN,13857.0,NaN
7005,43018402,Strayer University-Anne Arundel Campus,Millersville,MD,21108,NaN,NaN,13857.0,NaN
7006,43018403,Strayer University-White Marsh Campus,Baltimore,MD,21236,NaN,NaN,13857.0,NaN
7007,43018404,Strayer University-Owings Mills Campus,Owings Mills,MD,21117,NaN,NaN,13857.0,NaN

In [33]:
w = df[df["STABBR"] == "DC"]
w

,UNITID,INSTNM,CITY,STABBR,ZIP,ADM_RATE,UGDS,TUITIONFEE_IN,MN_EARN_WNE_P10
643,131159,American University,Washington,DC,20016-8001,0.2940,7433.0,46615.0,NaN
644,131283,The Catholic University of America,Washington,DC,20064,0.8258,3284.0,44060.0,NaN
645,131399,University of the District of Columbia,Washington,DC,20008,NaN,3606.0,5756.0,NaN
646,131405,Pontifical Faculty of the Immaculate Conceptio...,Washington,DC,20017-1585,NaN,NaN,NaN,NaN
647,131450,Gallaudet University,Washington,DC,20002-3695,0.5901,1111.0,16558.0,NaN
648,131469,George Washington University,Washington,DC,20052,0.4098,11718.0,53518.0,NaN
649,131496,Georgetown University,Washington,DC,20057-0001,0.1568,7128.0,52300.0,NaN
650,131520,Howard University,Washington,DC,20059-0001,0.4142,6276.0,25697.0,NaN
651,131803,Strayer University-District of Columbia,Washington,DC,20005,NaN,687.0,13857.0,NaN
652,131830,National Conservatory of Dramatic Arts,Washington,DC,20007,1.0000,32.0,9900.0,NaN
653,131876,Trinity Washington University,Washington,DC,20017-1094,0.9228,1498.0,23690.0,NaN
654,131973,Wesley Theological Seminary,Washington,DC,20016-5690,NaN,NaN,NaN,NaN
4100,363721,University of the District of Columbia-David A...,Washington,DC,20008,NaN,NaN,NaN,NaN
4348,384412,University of the Potomac-Washington DC Campus,Washington,DC,20005,NaN,65.0,13884.0,NaN
4616,420370,Career Technical Institute,Washington,DC,20005,NaN,387.0,NaN,NaN
4844,439473,Bennett Career Institute,Washington,DC,20017,NaN,312.0,NaN,NaN
5079,444893,Technical Learning Centers Inc,Washington,DC,20006-5540,NaN,172.0,NaN,NaN
5328,450483,University of Phoenix-Washington DC,Washington,DC,20001-1431,NaN,70.0,9960.0,NaN
5520,455804,Institute of World Politics,Washington,DC,20036,NaN,NaN,NaN,NaN
5521,455813,Pontifical John Paul II Institute for Studies ...,Washington,DC,20064,NaN,NaN,NaN,NaN
5739,459745,The Chicago School of Professional Psychology ...,Washington,DC,20005,NaN,NaN,NaN,NaN
5747,459994,Strayer University-Global Region,Washington,DC,20005,NaN,5543.0,13857.0,NaN
6727,13180301,Strayer University-Takoma Park Campus,Washington,DC,20012,NaN,NaN,13857.0,NaN
7094,47503313,Relay Graduate School of Education - Washingto...,Washington,DC,20002,NaN,NaN,NaN,NaN

In [34]:
de = df[df["STABBR"] == "DE"]
de

,UNITID,INSTNM,CITY,STABBR,ZIP,ADM_RATE,UGDS,TUITIONFEE_IN,MN_EARN_WNE_P10
634,130837,Margaret H Rollins School of Nursing at Beebe ...,Lewes,DE,19958,NaN,59.0,NaN,NaN
635,130873,Dawn Career Institute LLC,Newark,DE,19702,NaN,108.0,NaN,NaN
636,130907,Delaware Technical Community College-Terry,Dover,DE,19901,NaN,12408.0,4848.0,NaN
637,130934,Delaware State University,Dover,DE,19901,0.4518,3678.0,7868.0,NaN
638,130943,University of Delaware,Newark,DE,19716,0.6289,18948.0,13160.0,NaN
639,130989,Goldey-Beacom College,Wilmington,DE,19808,0.5177,770.0,23850.0,NaN
640,131061,Schilling-Douglas School of Hair Design LLC,Newark,DE,19711,NaN,133.0,NaN,NaN
641,131098,Wesley College,Dover,DE,19901-3875,0.6151,1342.0,26406.0,NaN
642,131113,Wilmington University,New Castle,DE,19720,NaN,8346.0,10940.0,NaN
4729,432524,Delaware College of Art and Design,Wilmington,DE,19801-3007,0.7900,143.0,25710.0,NaN
4917,441362,Harris School of Business-Wilmington Campus,Wilmington,DE,19803,NaN,219.0,NaN,NaN
5037,444200,Harris School of Business-Dover Campus,Dover,DE,19901,NaN,226.0,NaN,NaN
5275,449472,Delaware Learning Institute of Cosmetology,Dagsboro,DE,19939,NaN,39.0,NaN,NaN
5322,450298,Strayer University-Delaware,Newark,DE,19713,NaN,267.0,13857.0,NaN
5354,451051,Academy of Massage and Bodywork,Bear,DE,19701,NaN,95.0,NaN,NaN
5718,459301,Paul Mitchell the School-Delaware,Newark,DE,19702,NaN,103.0,NaN,NaN
6527,488262,Hair Academy School of Barbering & Beauty,Newark,DE,19713-2305,NaN,33.0,NaN,NaN
6725,13090701,Delaware Technical Community College-Owens,Georgetown,DE,19947,NaN,NaN,4848.0,NaN
6726,13090702,Delaware Technical Community College-Stanton/W...,Wilmington,DE,19801,NaN,NaN,4848.0,NaN
7084,47503303,Relay Graduate School of Education - Delaware,Wilmington,DE,19801,NaN,NaN,NaN,NaN

filtered dataset to a new file

In [35]:
five = pd.concat([p, w, m, de, v]) # concantenate all 5 datasets in one data frame
five

,UNITID,INSTNM,CITY,STABBR,ZIP,ADM_RATE,UGDS,TUITIONFEE_IN,MN_EARN_WNE_P10
2933,210474,Jolie Hair and Beauty Academy-Hazleton,Hazleton,PA,18201,NaN,61.0,NaN,NaN
2934,210492,Bryn Athyn College of the New Church,Bryn Athyn,PA,19009-0711,0.8755,323.0,21126.0,NaN
2935,210508,Academy of Vocal Arts,Philadelphia,PA,19103-6685,NaN,NaN,NaN,NaN
2936,210571,Albright College,Reading,PA,19612-5234,0.5004,1999.0,43454.0,NaN
2937,210599,All-State Career School,Essington,PA,19029,NaN,306.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
6969,24893411,ECPI University-Virginia Beach Health Sciences,Virginia Beach,VA,234621603,NaN,NaN,15261.0,NaN
6970,24893412,ECPI University-Richmond South,Richmond,VA,232361603,NaN,NaN,14985.0,NaN
6971,24893413,ECPI University-Innsbrook,Glen Allen,VA,230601603,NaN,NaN,15263.0,NaN
6972,24893414,ECPI University-Richmond West,Richmond,VA,232941603,NaN,NaN,16039.0,NaN
6973,24893415,ECPI University - Roanoke,Roanoke,VA,240121603,NaN,NaN,15525.0,NaN

In [37]:
five.to_csv('five_states_clgs.csv') # import dataframe to CSV

In [38]:
import csv
with open('five_states_clgs.csv', 'r') as file: # read csv file which we created to see
    reader = csv.reader(file)
    for row in reader:
         print(row)

['', 'UNITID', 'INSTNM', 'CITY', 'STABBR', 'ZIP', 'ADM_RATE', 'UGDS', 'TUITIONFEE_IN', 'MN_EARN_WNE_P10']
['2933', '210474', 'Jolie Hair and Beauty Academy-Hazleton', 'Hazleton', 'PA', '18201', '', '61.0', '', '']
['2934', '210492', 'Bryn Athyn College of the New Church', 'Bryn Athyn', 'PA', '19009-0711', '0.8755', '323.0', '21126.0', '']
['2935', '210508', 'Academy of Vocal Arts', 'Philadelphia', 'PA', '19103-6685', '', '', '', '']
['2936', '210571', 'Albright College', 'Reading', 'PA', '19612-5234', '0.5004', '1999.0', '43454.0', '']
['2937', '210599', 'All-State Career School', 'Essington', 'PA', '19029', '', '306.0', '', '']
['2938', '210605', 'Community College of Allegheny County', 'Pittsburgh', 'PA', '15233-1895', '', '14804.0', '4198.0', '']
['2939', '210669', 'Allegheny College', 'Meadville', 'PA', '16335-3902', '0.6789', '1764.0', '45970.0', '']
['2940', '210711', 'The  Beauty Institute', 'Allentown', 'PA', '18109-1629', '', '28.0', '', '']
['2941', '210739', 'DeSales University', 'Center Valley', 'PA', '18034-9568', '0.7379', '2291.0', '35900.0', '']
['2942', '210748', 'Altoona Beauty School Inc', 'Altoona', 'PA', '16602-6039', '', '53.0', '', '']
['2943', '210775', 'Alvernia University', 'Reading', 'PA', '19607-1799', '0.7081', '2231.0', '33640.0', '']
['2944', '210784', 'The Beauty Institute-Ambler', 'Ambler', 'PA', '19002', '', '115.0', '', '']
['2945', '210809', 'American College of Financial Services', 'King of Prussia', 'PA', '19406', '', '8354.0', '', '']
['2946', '210890', 'Antonelli Institute', 'Erdenheim', 'PA', '19038-8242', '', '71.0', '19890.0', '']
['2947', '210942', 'The Art Institute of Philadelphia', 'Philadelphia', 'PA', '19103-5198', '', '842.0', '17914.0', '']
['2948', '210951', 'Career Training Academy-Lower Burrell', 'Lower Burrell', 'PA', '15068', '', '130.0', '', '']
['2949', '210960', 'The Art Institute of Pittsburgh', 'Pittsburgh', 'PA', '15222', '', '431.0', '17626.0', '']
['2950', '211006', 'Automotive Training Center-Exton', 'Exton', 'PA', '19341-1310', '', '304.0', '', '']
['2951', '211024', 'Clarks Summit University', 'South Abington Township', 'PA', '18411-1250', '0.5508', '498.0', '23890.0', '']
['2952', '211079', 'Community College of Beaver County', 'Monaca', 'PA', '15061-2588', '', '1768.0', '5880.0', '']
['2953', '211088', 'Arcadia University', 'Glenside', 'PA', '19038-3295', '0.6229', '2233.0', '42330.0', '']
['2954', '211130', 'Missio Theological Seminary', 'Philadelphia', 'PA', '19123', '', '', '', '']
['2955', '211149', 'Bidwell Training Center Inc', 'Pittsburgh', 'PA', '15233', '0.8529', '141.0', '', '']
['2956', '211158', 'Bloomsburg University of Pennsylvania', 'Bloomsburg', 'PA', '17815', '0.7325', '8276.0', '10500.0', '']
['2957', '211200', 'Bradford School', 'Pittsburgh', 'PA', '15219', '0.9054', '352.0', '15380.0', '']
['2958', '211273', 'Bryn Mawr College', 'Bryn Mawr', 'PA', '19010', '0.3801', '1328.0', '50500.0', '']
['2959', '211291', 'Bucknell University', 'Lewisburg', 'PA', '17837', '0.3108', '3588.0', '53986.0', '']
['2960', '211307', 'Bucks County Community College', 'Newtown', 'PA', '18940-4106', '', '7257.0', '4418.0', '']
['2961', '211316', 'Bucks County School of Beauty Culture Inc', 'Feasterville', 'PA', '19053-7368', '', '72.0', '', '']
['2962', '211334', 'Butler Beauty Academy', 'Butler', 'PA', '16001', '', '20.0', '', '']
['2963', '211343', 'Butler County Community College', 'Butler', 'PA', '16002', '', '2803.0', '4800.0', '']
['2964', '211352', 'Cabrini University', 'Radnor', 'PA', '19087-3698', '0.7321', '1536.0', '31350.0', '']
['2965', '211361', 'California University of Pennsylvania', 'California', 'PA', '15419-1394', '0.961', '5435.0', '10840.0', '']
['2966', '211431', 'Carlow University', 'Pittsburgh', 'PA', '15213-3165', '0.9164', '1339.0', '28596.0', '']
['2967', '211440', 'Carnegie Mellon University', 'Pittsburgh', 'PA', '15213-3890', '0.222', '6434.0', '53910.0', '']
['2968', '211468', 'Cedar Crest College', 'Allentown', 'PA', '18104-6196', '0.6333', '1413.0', '38092.0', '']
['2969', '211477', 'Central Penn College', 'Summerdale', 'PA', '17093-0309', '0.789', '1188.0', '18174.0', '']
['2970', '211556', 'Chatham University', 'Pittsburgh', 'PA', '15232', '0.5455', '981.0', '36510.0', '']
['2971', '211583', 'Chestnut Hill College', 'Philadelphia', 'PA', '19118-2693', '0.9572', '1317.0', '35180.0', '']
['2972', '211608', 'Cheyney University of Pennsylvania', 'Cheyney', 'PA', '19319-0200', '', '722.0', '12104.0', '']
['2973', '211617', 'Brightwood Career Institute-Philadelphia Mills', 'Philadelphia', 'PA', '19154', '', '586.0', '', '']
['2974', '211635', 'Citizens School of Nursing', 'Tarentum', 'PA', '15084', '0.0', '158.0', '', '']
['2975', '211644', 'Clarion University of Pennsylvania', 'Clarion', 'PA', '16214', '0.9549', '4214.0', '10890.0', '']
['2976', '211802', 'DLP Conemaugh Memorial Medical Center', 'Johnstown', 'PA', '15905-4398', '0.8913', '228.0', '', '']
['2977', '211820', 'Consolidated School of Business-York', 'York', 'PA', '17404', '', '114.0', '', '']
['2978', '211893', 'Curtis Institute of Music', 'Philadelphia', 'PA', '19103', '0.033', '131.0', '2675.0', '']
['2979', '211909', 'Dean Institute of Technology', 'Pittsburgh', 'PA', '15226-1197', '', '151.0', '14550.0', '']
['2980', '211927', 'Delaware County Community College', 'Media', 'PA', '19063-1094', '', '11030.0', '5291.0', '']
['2981', '211981', 'Delaware Valley University', 'Doylestown', 'PA', '18901-2697', '0.664', '1908.0', '38000.0', '']
['2982', '212009', 'Dickinson College', 'Carlisle', 'PA', '17013-2896', '0.4871', '2339.0', '52955.0', '']
['2983', '212018', 'Pennsylvania State University-Dickinson Law', 'Carlisle', 'PA', '17013-2861', '', '', '', '']
['2984', '212045', 'Douglas Education Center', 'Monessen', 'PA', '15062', '', '229.0', '16029.0', '']
['2985', '212054', 'Drexel University', 'Philadelphia', 'PA', '19104', '0.7904', '15335.0', '52002.0', '']
['2986', '212106', 'Duquesne University', 'Pittsburgh', 'PA', '15282', '0.7170000000000001', '5930.0', '36394.0', '']
['2987', '212115', 'East Stroudsburg University of Pennsylvania', 'East Stroudsburg', 'PA', '18301-2999', '0.8356', '5972.0', '10098.0', '']
['2988', '212133', 'Eastern University', 'Saint Davids', 'PA', '19087-3696', '0.6561', '1837.0', '32145.0', '']
['2989', '212160', 'Edinboro University of Pennsylvania', 'Edinboro', 'PA', '16444-0001', '0.9253', '4229.0', '10282.0', '']
['2990', '212197', 'Elizabethtown College', 'Elizabethtown', 'PA', '17022-2298', '0.7402', '1647.0', '45350.0', '']
['2991', '212230', 'Empire Beauty School-Lebanon', 'Lebanon', 'PA', '17042', '', '41.0', '', '']
['2992', '212267', 'Empire Beauty School-York', 'York', 'PA', '17402', '', '84.0', '', '']
['2993', '212276', 'Empire Beauty School-Lancaster', 'Lancaster', 'PA', '17603', '', '78.0', '', '']
['2994', '212294', 'Empire Beauty School-Shamokin Dam', 'Shamokin Dam', 'PA', '17876', '', '46.0', '', '']
['2995', '212300', 'Empire Beauty School-Pottsville', 'Pottsville', 'PA', '17901', '', '52.0', '', '']
['2996', '212328', 'Empire Beauty  School-Lehigh Valley', 'Whitehall', 'PA', '18052', '', '103.0', '', '']
['2998', '212355', 'Empire Beauty School-Wyoming Valley', 'Moosic', 'PA', '18507', '', '141.0', '', '']
['2999', '212373', 'Empire Beauty School-Warminster', 'Warminster', 'PA', '18974', '', '28.0', '', '']
['3000', '212382', 'Empire Beauty School-Harrisburg', 'Harrisburg', 'PA', '17109', '', '123.0', '', '']
['3001', '212391', 'Empire Beauty School-Reading', 'Reading', 'PA', '19605', '', '119.0', '', '']
['3002', '212434', 'Erie Institute of Technology Inc', 'Erie', 'PA', '16565', '', '295.0', '13770.0', '']
['3003', '212443', 'Evangelical Theological Seminary', 'Myerstown', 'PA', '17067-1222', '', '', '', '']
['3005', '212568', 'Aria Health School of Nursing', 'Trevose', 'PA', '19053-6939', '', '200.0', '18585.0', '']
['3006', '212577', 'Franklin and Marshall College', 'Lancaster', 'PA', '17604-3003', '0.3411', '2269.0', '54380.0', '']
['3007', '212601', 'Gannon University', 'Erie', 'PA', '16541-0001', '0.799', '2616.0', '30932.0', '']
['3008', '212656', 'Geneva College', 'Beaver Falls', 'PA', '15010-3599', '0.6901', '1330.0', '26070.0', '']
['3009', '212674', 'Gettysburg College', 'Gettysburg', 'PA', '17325', '0.45799999999999996', '2411.0', '52640.0', '']
['3010', '212753', 'Empire Beauty School-NE Philadelphia', 'Philadelphia', 'PA', '19154', '', '144.0', '', '']
['3011', '212771', 'Gratz College', 'Melrose Park', 'PA', '19027-3010', '', '47.0', '', '']
['3012', '212805', 'Grove City College', 'Grove City', 'PA', '16127-2104', '0.7987', '2327.0', '17254.0', '']
['3013', '212832', 'Gwynedd Mercy University', 'Gwynedd Valley', 'PA', '19437-0901', '0.9377', '1987.0', '33600.0', '']
['3014', '212869', 'Harcum College', 'Bryn Mawr', 'PA', '19010-3470', '', '1436.0', '23670.0', '']
['3015', '212878', 'Harrisburg Area Community College', 'Harrisburg', 'PA', '17110-2999', '', '15968.0', '6473.0', '']
['3016', '212911', 'Haverford College', 'Haverford', 'PA', '19041-1392', '0.2005', '1291.0', '52994.0', '']
['3017', '212975', 'Commonwealth Technical Institute', 'Johnstown', 'PA', '15905-3092', '', '183.0', '16836.0', '']
['3018', '212984', 'Holy Family University', 'Philadelphia', 'PA', '19114-2009', '0.7075', '1904.0', '30346.0', '']
['3019', '212993', 'Hussian College School of Art', 'Philadelphia', 'PA', '19130', '0.6939', '52.0', '19650.0', '']
['3020', '213002', 'Brightwood Career Institute-Pittsburgh', 'Pittsburgh', 'PA', '15222', '', '250.0', '', '']
['3021', '213011', 'Immaculata University', 'Immaculata', 'PA', '19345', '0.8294', '1383.0', '27350.0', '']
['3022', '213020', 'Indiana University of Pennsylvania-Main Campus', 'Indiana', 'PA', '15705-1098', '0.9082', '9965.0', '12119.0', '']
['3023', '213163', 'UPMC Jameson School of Nursing', 'New Castle', 'PA', '16105', '', '46.0', '10781.0', '']
['3024', '213181', 'Great Lakes Institute of Technology', 'Erie', 'PA', '16509-2482', '0.7593', '396.0', '', '']
['3025', '213215', 'Jolie Hair and Beauty Academy-Wilkes-Barre', 'Wilkes Barre', 'PA', '18702', '', '169.0', '', '']
['3026', '213233', 'Johnson College', 'Scranton', 'PA', '18508-1495', '0.9644', '446.0', '18567.0', '']
['3027', '213251', 'Juniata College', 'Huntingdon', 'PA', '16652-2196', '0.7077', '1371.0', '43875.0', '']
['3028', '213303', 'Keystone College', 'La Plume', 'PA', '18440-0200', '0.9440000000000001', '1274.0', '26670.0', '']
['3029', '213321', "King's College", 'Wilkes-Barre', 'PA', '18711-0801', '0.7092', '2065.0', '35830.0', '']
['3030', '213330', 'Butler Beauty Academy-Kittanning Beauty Academy', 'Kittanning', 'PA', '16201', '', '8.0', '', '']
['3031', '213349', 'Kutztown University of Pennsylvania', 'Kutztown', 'PA', '19530-0730', '0.8314', '7443.0', '9987.0', '']
['3032', '213358', 'La Roche University', 'Pittsburgh', 'PA', '15237-5898', '0.9657', '1312.0', '27720.0', '']
['3033', '213367', 'La Salle University', 'Philadelphia', 'PA', '19141-1199', '0.7927', '3708.0', '29500.0', '']
['3034', '213376', 'Lackawanna College', 'Scranton', 'PA', '18509-3206', '', '1506.0', '15160.0', '']
['3035', '213385', 'Lafayette College', 'Easton', 'PA', '18042-1768', '0.3081', '2567.0', '51600.0', '']
['3036', '213400', 'Lancaster Bible College', 'Lancaster', 'PA', '17601-5036', '0.7181', '1504.0', '22580.0', '']
['3037', '213446', 'Lancaster Theological Seminary', 'Lancaster', 'PA', '17603-2897', '', '', '', '']
['3038', '213455', 'Lancaster School of Cosmetology & Therapeutic Bodywork', 'Lancaster', 'PA', '17602', '', '185.0', '', '']
['3039', '213473', 'Lansdale School of Business', 'North Wales', 'PA', '19454-4114', '', '163.0', '10800.0', '']
['3040', '213491', 'Lansdale School of Cosmetology Inc', 'Lansdale', 'PA', '19446-2003', '', '53.0', '', '']
['3041', '213507', 'Lebanon Valley College', 'Annville', 'PA', '17003-1400', '0.73', '1658.0', '42180.0', '']
['3042', '213525', 'Lehigh Carbon Community College', 'Schnecksville', 'PA', '18078-2598', '', '5588.0', '3990.0', '']
['3043', '213534', 'Platt College-Berks Technical Institute', 'Wyomissing', 'PA', '19610-1168', '', '724.0', '11260.0', '']
['3044', '213543', 'Lehigh University', 'Bethlehem', 'PA', '18015', '0.2515', '5057.0', '50740.0', '']
['3045', '213552', 'Levittown Beauty Academy', 'Levittown', 'PA', '19054', '', '91.0', '', '']
['3046', '213570', 'Lincoln Technical Institute-Allentown', 'Allentown', 'PA', '18104-9889', '', '444.0', '', '']
['3047', '213589', 'Lincoln Technical Institute-Philadelphia', 'Philadelphia', 'PA', '19136', '', '246.0', '', '']
['3048', '213598', 'Lincoln University', 'Lincoln University', 'PA', '19352-0999', '0.7968', '1994.0', '11379.0', '']
['3049', '213613', 'Lock Haven University', 'Lock Haven', 'PA', '17745-2390', '0.8904', '3425.0', '10576.0', '']
['3050', '213622', 'St Margaret School of Nursing', 'Pittsburgh', 'PA', '15238-3250', '0.5714', '92.0', '15315.0', '']
['3051', '213631', 'United Lutheran Seminary', 'Gettysburg', 'PA', '17325-1795', '', '', '', '']
['3052', '213659', 'Luzerne County Community College', 'Nanticoke', 'PA', '18634-3899', '', '4758.0', '5160.0', '']
['3053', '213668', 'Lycoming College', 'Williamsport', 'PA', '17701-5192', '0.6403', '1192.0', '38618.0', '']
['3054', '213774', 'Manor College', 'Jenkintown', 'PA', '19046-3399', '0.9255', '602.0', '17029.0', '']
['3055', '213783', 'Mansfield University of Pennsylvania', 'Mansfield', 'PA', '16933', '0.8919', '1770.0', '12316.0', '']
['3056', '213826', 'Marywood University', 'Scranton', 'PA', '18509-1598', '0.7512', '1835.0', '33940.0', '']
['3057', '213871', 'McCann School of Business & Technology', 'Hazle Township', 'PA', '18202', '', '168.0', '11292.0', '']
['3058', '213914', 'Vet Tech Institute', 'Pittsburgh', 'PA', '15222-3400', '', '343.0', '14980.0', '']
['3059', '213932', 'Roxborough Memorial Hospital School of Nursing', 'Philadelphia', 'PA', '19128', '', '142.0', '', '']
['3060', '213987', 'Mercyhurst University', 'Erie', 'PA', '16546', '0.6992', '2448.0', '36320.0', '']
['3061', '213996', 'Messiah College', 'Mechanicsburg', 'PA', '17055', '0.7701', '2670.0', '34160.0', '']
['3062', '214023', "The Workforce Institute's City College", 'Philadelphia', 'PA', '19140-2302', '1.0', '21.0', '12097.0', '']
['3063', '214041', 'Millersville University of Pennsylvania', 'Millersville', 'PA', '17551-0302', '0.7949', '6613.0', '11858.0', '']
['3064', '214069', 'Misericordia University', 'Dallas', 'PA', '18612-1098', '0.7879', '2100.0', '31660.0', '']
['3065', '214111', 'Montgomery County Community College', 'Blue Bell', 'PA', '19422-0796', '', '8948.0', '5730.0', '']
['3066', '214148', 'Moore College of Art and Design', 'Philadelphia', 'PA', '19103-1179', '0.5407', '373.0', '39833.0', '']
['3067', '214157', 'Moravian College', 'Bethlehem', 'PA', '18018-6650', '0.7597', '2007.0', '42024.0', '']
['3068', '214166', 'Mount Aloysius College', 'Cresson', 'PA', '16630-1999', '0.9107', '1185.0', '22430.0', '']
['3069', '214175', 'Muhlenberg College', 'Allentown', 'PA', '18104', '0.4836', '2329.0', '50830.0', '']
['3070', '214254', 'Brightwood Career Institute-Philadelphia', 'Philadelphia', 'PA', '19104', '', '421.0', '', '']
['3071', '214272', 'Neumann University', 'Aston', 'PA', '19014-1298', '0.9628', '1997.0', '30050.0', '']
['3072', '214290', 'New Castle School of Trades', 'New Castle', 'PA', '16101', '1.0', '763.0', '', '']
['3073', '214379', 'Northampton County Area Community College', 'Bethlehem', 'PA', '18020-7599', '', '9203.0', '4230.0', '']
['3074', '214476', 'Ohio Valley Hospital School of Nursing', 'McKees Rocks', 'PA', '15136', '0.8', '76.0', '16300.0', '']
['3075', '214528', 'Orleans Technical College', 'Philadelphia', 'PA', '19114-1014', '0.5728', '289.0', '', '']
['3076', '214564', 'Salus University', 'Elkins Park', 'PA', '19027-6262', '', '', '', '']
['3077', '214582', 'Pennsylvania Institute of Technology', 'Media', 'PA', '19063-4098', '', '447.0', '13230.0', '']
['3078', '214591', 'Pennsylvania State University-Penn State Erie-Behrend College', 'Erie', 'PA', '16563-0001', '0.8891', '4283.0', '15190.0', '']
['3079', '214607', 'Pennsylvania State University-Penn State Great Valley', 'Malvern', 'PA', '19355-1488', '', '', '', '']
['3080', '214616', 'Pennsylvania State University-College of Medicine', 'Hershey', 'PA', '17033-2360', '', '', '', '']
['3081', '214625', 'Pennsylvania State University-Penn State New Kensington', 'New Kensington', 'PA', '15068-1765', '0.7676', '573.0', '13694.0', '']
['3082', '214634', 'Pennsylvania State University-Penn State Shenango', 'Sharon', 'PA', '16146-1537', '0.7428', '345.0', '13324.0', '']
['3083', '214643', 'Pennsylvania State University-Penn State Wilkes-Barre', 'Lehman', 'PA', '18627-0217', '0.8245', '404.0', '13568.0', '']
['3084', '214652', 'Pennsylvania State University-Penn State Scranton', 'Dunmore', 'PA', '18512-1602', '0.7792', '1003.0', '14460.0', '']
['3085', '214670', 'Pennsylvania State University-Penn State Lehigh Valley', 'Center Valley', 'PA', '18034-8447', '0.8534', '823.0', '14460.0', '']
['3086', '214689', 'Pennsylvania State University-Penn State Altoona', 'Altoona', 'PA', '16601-3777', '0.9225', '3451.0', '15190.0', '']
['3087', '214698', 'Pennsylvania State University-Penn State Beaver', 'Monaca', 'PA', '15061-2764', '0.8131', '598.0', '13694.0', '']
['3088', '214704', 'Pennsylvania State University-Penn State Berks', 'Reading', 'PA', '19610-1016', '0.857', '2635.0', '15190.0', '']
['3089', '214713', 'Pennsylvania State University-Penn State Harrisburg', 'Middletown', 'PA', '17057-4846', '0.8375', '4223.0', '15190.0', '']
['3090', '214731', 'Pennsylvania State University-Penn State Brandywine', 'Media', 'PA', '19063-5522', '0.8703', '1366.0', '14460.0', '']
['3091', '214740', 'Pennsylvania State University-Penn State DuBois', 'DuBois', 'PA', '15801-2549', '0.8387', '497.0', '13632.0', '']
['3092', '214759', 'Pennsylvania State University-Penn State Fayette- Eberly', 'Lemont Furnace', 'PA', '15456-1025', '0.8214', '649.0', '13632.0', '']
['3093', '214768', 'Pennsylvania State University-Penn State Hazleton', 'Hazleton', 'PA', '18202-8025', '0.9352', '699.0', '14460.0', '']
['3094', '214777', 'Pennsylvania State University-Main Campus', 'University Park', 'PA', '16802-1503', '0.5031', '40553.0', '18436.0', '']
['3095', '214786', 'Pennsylvania State University-Penn State Greater Allegheny', 'McKeesport', 'PA', '15132-7644', '0.8187', '488.0', '13694.0', '']
['3096', '214795', 'Pennsylvania State University-Penn State Mont Alto', 'Mont Alto', 'PA', '17237-9700', '0.7476', '759.0', '13694.0', '']
['3097', '214801', 'Pennsylvania State University-Penn State Abington', 'Abington', 'PA', '19001-3918', '0.8523', '3674.0', '14516.0', '']
['3098', '214810', 'Pennsylvania State University-Penn State Schuylkill', 'Schuylkill Haven', 'PA', '17972-2202', '0.7555', '695.0', '14398.0', '']
['3099', '214829', 'Pennsylvania State University-Penn State York', 'York', 'PA', '17403-3326', '0.825', '899.0', '14460.0', '']
['3100', '214883', 'Peirce College', 'Philadelphia', 'PA', '19102-4699', '', '1381.0', '15060.0', '']
['3101', '214892', 'Penn Commercial Business/Technical School', 'Washington', 'PA', '15301-6822', '0.9539', '225.0', '20000.0', '']
['3102', '214944', 'Pennco Tech-Bristol', 'Bristol', 'PA', '19007', '', '315.0', '', '']
['3103', '214971', 'Pennsylvania Academy of the Fine Arts', 'Philadelphia', 'PA', '19102-1510', '0.927', '188.0', '37096.0', '']
['3104', '215008', 'Pennsylvania Gunsmith School', 'Pittsburgh', 'PA', '15202-2637', '', '79.0', '', '']
['3105', '215044', 'Cortiva Institute-King of Prussia', 'King of Prussia', 'PA', '19406', '', '172.0', '', '']
['3106', '215053', 'Pennsylvania College of Art and Design', 'Lancaster', 'PA', '17608-0059', '0.5', '257.0', '25000.0', '']
['3107', '215062', 'University of Pennsylvania', 'Philadelphia', 'PA', '19104-6303', '0.09300000000000001', '10660.0', '53534.0', '']